### ISSUE TITLE
Using `api` vrpProvider is considered invalid, it was reverted to default.

### ISSUE THREAD

**Issue by wibisono** [nttgin/BGPalerter#1005]
Hi,

I am trying to setup BGP alerter to read vrps from my own routinator instance, with the same config on the docs:
```
vrpProvider: api
url: http://127.0.0.1:8323/json
preCacheROAs: true
```

But I am getting the following error:
```
2023-01-06T13:49:30+00:00 error: The specified vrpProvider is not valid. Using default vrpProvider.
```

Tracing the error, it looks like `api` is [not recognized as one of the valid providers](https://github.com/nttgin/BGPalerter/blob/main/src/utils/rpkiUtils.js#L39), when bgp alerter is parsing the RPKI configurations.

Not sure how to patch it, maybe simplest is to recognized it as one possible providers in the [rpki-validator](https://github.com/massimocandela/rpki-validator/blob/main/src/index.js#L14) helper, or change the logic in parsing this parameter.

Cheers,

**Comment by massimocandela** [comment]
Hi @wibisono,

I hope all is good with you! Thanks for reporting this, at some point I refactored the validation of the provider parameter and I created this regression. It is now fixed in `dev`, it will go out with the next release.

**Comment by massimocandela** [comment]
This is now in the pre-release [v1.31.2](https://github.com/nttgin/BGPalerter/releases/tag/v1.31.2)
