### ISSUE TITLE
Speed up generate function

### ISSUE THREAD

**Issue by ancker010** [nttgin/BGPalerter#1082]
**Describe what you would like to achieve**
Provide a mechanism to speed up generation of large numbers of prefixes or ASNs.

**Describe why the current solution (if any) is not satisfactory**
When passing a large number of ASNs or Prefixes to the `generate` function, the process takes several hours.

**Provide an example**
```
time ./bin/bgpalerter-macos-x64 generate -m -l .output/prefixes.txt -o output/prefixes-test.yml
real    245m27.073s
user    8m16.969s
sys     1m10.959s
```

**Your information**
Ryan Harden: AS11537

**Comment by massimocandela** [comment]
Hi @ancker010,

What does prefixes.txt contains and how many ASes are you monitoring?

**Comment by ancker010** [comment]
`prefixes.txt` is a list of prefixes, one per line, currently 6887.
And approximately 1045 ASNs.
