### ISSUE TITLE
Publish to Debian repository and/or build Debian package in CI

### ISSUE THREAD

**Issue by WilliamDEdwards** [nttgin/BGPalerter#1111]
**Describe what you would like to achieve**

See title.

**Describe why the current solution (if any) is not satisfactory**

Currently, users must build the Debian package themselves. Not a huge hassle, but suboptimal. Publishing the package to a repository solves this. Alternatively, the package could simply be built in CI, for the `.deb` file to be published as a release asset aside from the binaries.

**Provide an example**

N/A

**Your information**

Cyberfusion, AS204983

**Comment by massimocandela** [comment]
Hi @WilliamDEdwards, this is done based on the PR or @b4ldr. It will go out with the next release.
