### ISSUE TITLE
Upgrade script overwrites upgrade.log instead of appending

### ISSUE THREAD

**Issue by davemidd** [nttgin/BGPalerter#1173]
**Describe the bug**
The upgrade script overwrites upgrade.log each time it is run, instead of appending to the log.

**Provide an example**
N/A

**Expected behavior**
The log should be appended to each time the script is run.

**Are you using the binary or the source code?**
Using the code provided at https://github.com/nttgin/BGPalerter/blob/main/docs/linux-service.md#automatic-updates

I believe the line:
`exec 1> $LOGS/upgrade.log 2>&1`
should be:
`exec 1>> $LOGS/upgrade.log 2>&1`

**Your information**
David Middleton

**Comment by massimocandela** [comment]
You are correct. Thanks for reporting.
