### ISSUE TITLE
Upgrade of node.js 

### ISSUE THREAD

**Issue by prajaktapatil60** [nttgin/BGPalerter#1183]
The version of Node.js installed for bgp-alerter application is prior to 16.20.2, 18.17.1, 20.5.1. 
/opt/bgpalerter # node -v
v18.14.0

It is, therefore, affected by multiple vulnerabilities.

Could you please upgrade it to the latest node.js version.

**Comment by massimocandela** [comment]
Every new release of BGPalerter comes with the updated node version.
The vulnerabilities I see reported for node 18.14 impact the experimental policy mechanism, which I'm not using (and they require anyway to run arbitrary code) [1]. I do not see any reason to rush a release. However, cves are sometimes difficult to digest and I may be missing something. If you are worried about something specific that you can explain, open again the ticket and I'll see what I can do.

Btw, I believe in your installation, you could upgrade node by yourself.

[1] https://nodejs.org/en/blog/release/v18.17.1
