### ISSUE TITLE
Add Auto-Submitted: auto-generated email header

### ISSUE THREAD

**Issue by XioNoX** [nttgin/BGPalerter#1194]
**Describe what you would like to achieve**
Email sent by bgpalerter should have the `Auto-Submitted: auto-generated` header.
That's following https://datatracker.ietf.org/doc/html/rfc3834.

**Describe why the current solution (if any) is not satisfactory**
This is of course minor, but vacation auto-responders skip emails with that header defined.
Currently if BGPalerter sends a notification email, with a shared (eg. team) "from" email address. All the team will also receive an auto-responder email from people on vacations.

**Your information**
Arzhel, Wikimedia/AS14907

Thanks

**Comment by massimocandela** [comment]
Hi @XioNoX, thanks for this suggestion. This will go out with the next release.
