### ISSUE TITLE
Feature request: ignore certain hijacks

### ISSUE THREAD

**Issue by teunvink** [nttgin/BGPalerter#12]
We assigned a /24 from one of our /19's to one of our customers, who is multihomed and announces that /24 from their ASN instead of ours.

At this moment, when monitoring the /19 we get hijack notifications. Would it be possible to add some list of prefixes to be ignored, preferably specific combinations of prefix + ASN, so we do get alerts for "real" hijacks, but not for this one? Of course, we could filter this in the notification handler on our side, but it would make more sense not to generate notifications for known .

**Comment by massimocandela** [comment]
This can currently be done with a rule in prefixes.yml

x.x.x.x/24:
asn: customer_asn, my_asn
ignoreMorespecifics: true
