### ISSUE TITLE
Add option to ignore RIS update messages from specific peers

### ISSUE THREAD

**Issue by tomsiewert** [nttgin/BGPalerter#1217]
**Describe what you would like to achieve**
I need to ignore one / multiple RIPE RIS feeder (either the ASN or the IP of the feeder).

**Describe why the current solution (if any) is not satisfactory**
Some RIPE RIS feeder push stale/wrong data causing false-positive alerts for us. Unfortunately, this specific feeder does not reply to any of our messages to solve it that way. To decrease the amount of false-positive alerts, it'd be cool to exclude either specific ASNs as feeder or specific source feeder IPs.

In our case, it causes alerts like "ASxyz is announcing PREFIX but this prefix is not in the configured list of announced prefixes".

**Comment by massimocandela** [comment]
Hi @tomsiewert,

Can you elaborate on this? In particular:
1) What stale data means in this case? 
2) Did you check the single BGP updates the feeder sent?
3) Did you contact RIPE RIS?
4) Can you share the feeder AS? (also in private if you prefer)

Thanks

**Comment by tomsiewert** [comment]
Hi @massimocandela 

1. We have withdrawn two prefixes several weeks ago and they're also not visible in the DFZ anymore however, this feeder is still sending BGP UPDATE messages to RIPE RIS.
2. I did
3. Contacting RIPE is tbd
4. I'll send you an email

**Comment by massimocandela** [comment]
This will go out in the next release (see `blacklistSources` in `config.example.yml`). A private conversation is going on to better understand the situation that triggered this ticket.
