### ISSUE TITLE
Please configure tag and branch-based Docker builds 

### ISSUE THREAD

**Issue by mirceaulinic** [nttgin/BGPalerter#123]
**Describe what you would like to achieve**

It'd be great to have the Docker image tagged per release and branch. This way, you can pin to a specific version to avoid confusion and unexpected side effects.

**Describe why the current solution (if any) is not satisfactory**

Currently, everything merged into `dev` seems to get pushed under the `latest` tag: https://hub.docker.com/r/nttgin/bgpalerter/tags

**Provide an example**

Here's the Docker hub config I have for a project of mine, which I think would work well for BGPalerter too (with some minor changes):

![Screenshot_2020-01-09 Docker Hub](https://user-images.githubusercontent.com/16694679/72057131-cd263200-32c5-11ea-8657-00e705748605.png)

Please let me know if you have any questions!

**Comment by massimocandela** [comment]
This is done, thanks for the suggestion.

**Comment by vincentbernat** [comment]
It seems only the dev branch gets updated. There is no  1.23.2 tag on Docker Hub. Could you check if everything is correctly configured? Thanks.

**Comment by vincentbernat** [comment]
Thanks Massimo!
