### ISSUE TITLE
report email configuration

### ISSUE THREAD

**Issue by cardosocristian** [nttgin/BGPalerter#1232]
**Describe the bug**
I'm trying to configure email sending in the tool, but I receive the two errors below

        port: 25
        secure: false # If true the connection will use TLS when connecting to server. If false it will be still possible doing connection upgrade via STARTTLS
        ignoreTLS: false # If true TLS will be completely disabled, including STARTTLS. Set this to true if you see certificate errors in the logs.

And I get the following log when trying to run an email send test:
2024-01-22T15:32:37+00:00 error: Error: unable to get local issuer certificate

If I use the configuration below:

        port: 25
        secure: false # If true the connection will use TLS when connecting to server. If false it will be still possible doing connection upgrade via STARTTLS
        ignoreTLS: true # If true TLS will be completely disabled, including STARTTLS. Set this to true if you see certificate errors in the logs.

And I get the following log when trying to run an email send test:
2024-01-22T16:52:33+00:00 error: Error: Invalid login: 504 5.7.4 Unrecognized authentication type

The type of authentication I am using is login.

Is there any other way to increase the debug for the email test, because when checking the email server, the login didn't even leave the daemon itself to try to hit the server.

I tried to force it using the tlsv1.2 version according to the nodemailer documentation, but I was also unsuccessful.
Do you have a more suitable configuration example for use?

**Comment by tangledhelix** [comment]
I suspect the 2nd error is caused by your mail server's security requirements. I'm not sure what mail service you're using, but I've seen servers which refuse to permit SMTP authentication over a plaintext connection (which is what your second configuration example would configure).

**Comment by cardosocristian** [comment]
In fact, my exchange email server does not accept configuration in plain text, but when trying to use it with secure true, an error occurs regarding openssl, in my VM I am running openssl 3.0, to generate this error, I modified the following lines in the settings:

         secure: true # If true the connection will use TLS when connecting to server. If false it will still be possible doing connection upgrade via STARTTLS
         ignoreTLS: false # If true TLS will be completely disabled, including STARTTLS. Set this to true if you see certificate errors in the logs.

         tls:
          rejectUnauthorized: false # Reject unauthorized certificates

`error: Error: C027C81FB97F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:`

Before opening the issue, I did a lot of research, but I didn't find anything relevant that would give me a way forward.

**Comment by massimocandela** [comment]
Hi @cardosocristian,

I don't believe this to be a bug as per the label you placed. It is a support request.
Unfortunately, I don't have a way to answer your request. The email report is by far the most used, working on many installations. I would suggest you to check your app password, 2fa policies, the proper functioning of the server cert chain, and used port, but I don't have a way to further investigate this. You could try to use the v1.33 in pre-release and see if the new nodemailer does the trick.

**Comment by cardosocristian** [comment]
Hi @massimocandela
Okay, I'll close this issue then.

**Comment by massimocandela** [comment]
not necessarily, maybe somebody else had a similar experience and can share the configuration used :) In any case, if you do the tests above and find a solution, please report back here.
