### ISSUE TITLE
Add support for ARM64

### ISSUE THREAD

**Issue by potvinp** [nttgin/BGPalerter#1272]
**Describe what you would like to achieve**
Currently, BGPalerter is only released with support for the AMD64 platform. It would be wise to implement releases for the ARM64 platform due to the increasing popularity of ARM64-based devices and cloud services.

**Provide an example**
For the docker build at least, the only change required in the Dockerfile appears to be to utilize `arm64v8/node:18.19.0-alpine` as the source image for the ARM64 version instead of the `node:18.19.0-alpine` image it currently uses which is limited to AMD64.

I have made this change myself to allow BGPalerter to operate on an ARM64-based cloud server, which appears to be working without issues.

**Your information**
AS52210
Accuris Technologies Ltd.

**Comment by massimocandela** [comment]
Hi @potvinp,

Since it looks like you already worked on this. Please, provide a pull request with the docker changes and the pkg (for the binary) changes.

**Comment by kolobus** [comment]
Sorry for reopening old issue.

My test shows that zero repo modifications needed for supporting ARM64. My manual Docker build went flawlessly and bgpalerter now works on ARM VM.

Only adjustment needed is pipline which builds container and publishes it to Docker Hub. It should use multiarch docker build  instead of simple one.

**Comment by lukastribus** [comment]
Can this be reopened?

AFAIK the modifications needed are not in files in this repository so a PR against it is not possible?

**Comment by massimocandela** [comment]
The ARM version is available since last year in the release section.

**Comment by lukastribus** [comment]
Only for MacOS though, for Linux there is only the amd64 binary.

Also the docker container nttgin/bgpalerter is amd64 only.

**Comment by kolobus** [comment]
I can confirm that I locally built arm64 using docker and it perfectly runs on arm64 (Oracle Ampere).
