### ISSUE TITLE
Feature request: ignore more specifics only when matching a specific AS-path and prefix length

### ISSUE THREAD

**Issue by teunvink** [nttgin/BGPalerter#13]
We do DDoS mitigation by announcing a more specific (/24) covering the IP address under attack to a scrubbing center. Now, this triggers a 'possible change of configuration' notification, and the only way to solve that is to set 'ignoreMoreSpecifics' to 'true'. That would be unwanted though, since we would like to detect paths made up by 'BGP optimizers'.

Would it be possible to ignore a more specific *only* if it matches a specific prefix length and AS-path $SCRUBBING_CENTER $MY_ASN.

**Comment by job** [comment]
To phrase it differently, what's new here is to not only look at the Origin ASN in the AS_PATH, but also take into consideration the penultimate AS SEQUENCE in the AS_PATH?

**Comment by teunvink** [comment]
> To phrase it differently, what's new here is to not only look at the Origin ASN in the AS_PATH, but also take into consideration the penultimate AS SEQUENCE in the AS_PATH?

Yes, that's correct.

**Comment by massimocandela** [comment]
Hi, 
I don't get something here:

**Comment by massimocandela** [comment]
Hi, I don't get something here: if you declare in prefixes.yml both the less specific and the more specific, both with the correct origin AS, is it not already solving your case?

**Comment by teunvink** [comment]
Maybe I didn't explain it correctly. Hopefully this helps:

Normally I advertise my prefixes coming from AS12859, and I announce 'large' prefixes (/19's for example).

When under attack, I announce a more specific /24 for the target *only* to AS200020 (Nawas, our scrubbing center). This will divert traffic towards the target, they scrub it and everybody's happy.

So, in the global routing table, /24's from those /19's should only be seen with AS-path `.* 200020 12859$`.

Any other path for /24's from those larger blocks should be considered bad, most likely they're routes fabricated by some BGP optimizer and leaked to the global routing table.

So the origin of the prefix doesn't change, I want detect if those more specifics are actually mitigations via our scrubbing centers (which I expect, don't need alerts for) or something else.

Is it more clear now?

**Comment by massimocandela** [comment]
Thanks for the explanation. I got it now.
This is a variation of a feature BGPalerter doesn't support yet. Because we are not checking AS paths for now. This is why I was not getting it.
I'm already working on AS path matching so I add this request in the queue.

**Comment by teunvink** [comment]
Thanks, I appreciate that!

**Comment by lukastribus** [comment]
I agree this is a common use-case for everyone expect Tier 1 and scrubbing services themselves, so yes, this would be great.

**Comment by massimocandela** [comment]
Released in https://github.com/nttgin/BGPalerter/releases/tag/v1.20.0
