### ISSUE TITLE
Testing other monitoring?

### ISSUE THREAD

**Issue by LucasKiller** [nttgin/BGPalerter#1308]
Hello there!

I am using the latest version of BGPalerter these days and I really appreciate this software in our community, however, I'm having troubles to test it.

Is there any way that I could test other monitoring, like RPKI,  instead of default hijack test made by ./bgpalerter-linux-x64 -t?

Lucas

**Comment by massimocandela** [comment]
Hi @LucasKiller,

`npm run test` will test all the monitoring options (and more).
`-t` will test your reports configuration (only with hijacks, the goals is to test if you receive something, not the alert itself).
