### ISSUE TITLE
withdrawal notification via email

### ISSUE THREAD

**Issue by s2105** [nttgin/BGPalerter#149]
Hello,

We setup BGPalerter ubuntu instances (18.04). We are not getting an email alert when the withdrawal of our prefixes via email, but we are getting alert from our subscription with bgpmon when it is detected by 16 peers. 
We tested email from local ubuntu instance is working fine. 

Any help will be much appreciated.

**Comment by massimocandela** [comment]
Hello,

You should provide more information.

* Do you have configured reportFile also? Do you see the alerts in the report files?
* Can you see any log in the error files?
* What version do you use?
* Do you use the binary or the source code?

**Comment by s2105** [comment]
> Hello,
> 
> You should provide more information.
> 
> * Do you have configured reportFile also? Do you see the alerts in the report files?
Yes, I have configured reportFile, doesn't see an alert in the files. 

> * Can you see any log in the error files?
No, I don't see it in the logs. 
> * What version do you use?
1.23.2

> * Do you use the binary or the source code?
binary

**Comment by massimocandela** [comment]
> * Do you have configured reportFile also? Do you see the alerts in the report files?
>   Yes, I have configured reportFile, I can see an alert in the report log.

This means that everything is ok on the detection side.
Something is not configured properly in the email settings for reportEmail.
The error log files should tell you what is wrong. Additionally you can check https://nodemailer.com/smtp/ for a list of all the smtp parameters available.
Try to temporarily set `ignoreTLS ` to true to check if something is wrong with tls.

**Comment by s2105** [comment]
@massimocandela : Thank you very much for your response.
