### ISSUE TITLE
Prefix matching bug

### ISSUE THREAD

**Issue by sonicepk** [nttgin/BGPalerter#158]
**Describe the bug**
The matching of more specific prefixes is not working correctly. Below is an example where a hijack alert is generated where BGPalerter matches a prefix 193.105.222.0/24 to a /16 (193.1.0.0/16) which it does not belong to. 

**Provide an example**
The following is the hijack message that is logged:
"hijack
A new prefix 193.105.222.0/24 is announced by AS50762. It should be instead 193.1.0.0/16 (HEAnet) announced by AS1213"

From: prefixes.yml
193.1.0.0/16:
  description: HEAnet
  asn: 1213
  ignoreMorespecifics: false
  ignore: false

From: config.yml
options:
  monitorASns:
    1213:
      group: default

**Expected behavior**
There should be no match for 193.105.222.0/24 for the super net 193.1.0.0/16. There appears to be a partial string match for "193.1" but this is clearly not correct.

**Are you using the binary or the source code?**
Yes, the Linux binary on Ubuntu 18.04. https://github.com/nttgin/BGPalerter/releases/download/v1.23.2/bgpalerter-linux-x64
BGPalerter, version: 1.23.2 environment: production

**Your information**
Eoin Kenny
HEAnet 
AS1213

**Comment by massimocandela** [comment]
Hi Eoin,

Thanks for reporting.
I'm trying to reproduce this without success.
I tried to craft BGP messages with the same information you reported, and they get correctly discarded.

The prefix match happens at two levels: 
1) RIPE RIS, which sends the data to BGPalerter.
2) BGPalerter, which checks if any rule is matched.

There is no string match, both filters are done in binary with the netmask.
For the bug described to happen both filters have to be somehow bypassed.


Are you sure in prefix.yml you only have such rule? (Could you please provide me with the entire prefix.yml and config.yml?)

Anyway, the option `monitorASns` has to be placed in prefix.yml and not in config.yml

**Comment by sonicepk** [comment]
Hi Massimo,

Thank you for taking the time to look at this. 
My config.yml and prefixes.yml can be found here:
https://gist.github.com/sonicepk/d6501ad1db175fdd7dcf835ba244a7c1

I have only made one change which is to remove the web hook url for slack. 

Regards
Eoin

**Comment by massimocandela** [comment]
Thanks.

I am now monitoring exactly what you are doing. My only purpose is to replicate the specific issue.
Please inform me if the issue happens again on your side.

**Comment by massimocandela** [comment]
Could you provide me with the time when the log was issued? Possibly from the log files, copy the entire line. Thanks

**Comment by sonicepk** [comment]
Hi Massimo,

Yesterday the 4th of Feb at 11:00 GMT.
Thanks for investigating.

Regards
Eoin

**Comment by massimocandela** [comment]
Hello Eoin,

I have been running 4 instances of BGPalerter on your configuration (1 source code, 1 binary, 1 binary including 193.105/16, 1 source code logging all messages) for the last 48 hours.
I received plenty of BGP announcements from `193.105.222.0/24` (and other prefixes) but none of them triggered any alert. One of the BGPalerter was just listening and logging the announcements, so I am sure that such BGP messages reached the BGPalerter client and got correctly discarded.

Additionally I have created a test script to generate BGP announcements for ALL prefixes (from /16 to /26) in the v4 address space. This script feeds the BGP messages to BGPalerter. The gaol was to exhaustively check if any of them erroneously matched with 193.1/16. All the reported alerts are correct sub prefixes of 193.1/16.

At this point I have the suspect that the log has been generated by an unpatched version of BGPalerter (v1.23.2 solves a somehow related problem in ipv6). Please, check if you were/are running another instance of BGPalerter prior to v1.23.2 (e.g. 1.23.1 running in background). From my side, I have compiled again the latest release "just in case".

I anyway cannot underestimate this report, a lot of changes happened in the data management/cache in the last release so corner case bugs are always possible.
For this reason, could you please:
* kill all instances of BGPalerter
* delete the current binary
* in config.yml set `persistAlertData` to true
* download again the v1.23.2 binary from the releases page and run it

If it happens again after following the steps before, please reopen the issue and send to me the log lines in the log files and the json in alertdata (generated by the option persistAlertData). You can also send it to me by email.

Thanks

Ciao,
Massimo
