### ISSUE TITLE
reportAlerta not send any alert to ALERTA.io 

### ISSUE THREAD

**Issue by fjbanderas** [nttgin/BGPalerter#161]
My config.yml

- file: reportAlerta
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
    params:
      severity:
        hijack: critical
        newprefix: informational
        visibility: debug
        path: trace
      resource_templates:
        default: "${type}"
        hijack: "hijack::${prefix}@@${asn}"
        newprefix: "newprefix::${prefix}@@${asn}"
        visibility: "visibility::${prefix}@@${asn}"
      urls:
        default: "http://my_ip:5000/api/"

The log received this message:

2020-02-17T08:56:43+01:00 error: Error: Request failed with status code 403

I tried change my url to 

"http://my_ip:5000/"
"http://my_ip:5000/api"

but it doesn't work.
 
Any idea?

**Comment by mirceaulinic** [comment]
If you run `curl http://my_ip:5000/api/alerts` from the same place you're running BGPalerter, it should indicate or hint the culprit. Perhaps you need an API key or bearer token for authentication (or something else).

**Comment by fjbanderas** [comment]
I have executed the curl and it works without the need for API key
curl -XPOST http://myip:port/api/alert -H 'Content-type: application/json' -d@alert.json

**Comment by massimocandela** [comment]
I did some changes to the headers, please try to run: https://filebin.net/ocr6qrkwo4giiqk2/bgpalerter-linux-x64?t=ymjlpl8k

**Comment by fjbanderas** [comment]
Thanks, tomorrow I try it

**Comment by fjbanderas** [comment]
I have updated the file, but there is an error in the log. It tells me to update the config.yml file.

2020-02-18T08:28:38+01:00 info: The resource_templates parameter has been renamed in resourceTemplates. Please update your config.yml file

What changes do I have to make in the config file?

**Comment by massimocandela** [comment]
You can ignore that (in any case, the warning tells you exactly what to do: s/resource_templates/resourceTemplates).

**Comment by fjbanderas** [comment]
The error does not appear in the log, but I still do not receive alerts to ALERT.io

**Comment by massimocandela** [comment]
The fact you receive a 403 means that BGPalerter is doing the query but alerta is rejecting it (forbidden). Can you share the content of alert.json?
I would try to add an api key to see if in that case it works.

**Comment by fjbanderas** [comment]
I attach the alert.txt file (alert.json) and the config.txt file (config.yml).
The alert.json file was an example for you to see that the curl works.

In reference to the alerts I would like to receive. I would like to have the same ones that I am receiving in my syslog and in my mail.

[alert.txt](https://github.com/nttgin/BGPalerter/files/4219456/alert.txt)
[config.txt](https://github.com/nttgin/BGPalerter/files/4219459/config.txt)

**Comment by massimocandela** [comment]
I edited your post, you just posted your smtp credential in clear. I would suggest you to change them.

I will try to apply your config anyway to see what happens (except the email part)

**Comment by fjbanderas** [comment]
Thanks.
I will change my credentials

**Comment by mangelft** [comment]
Hi Massimo,

I've been helping Fran to debug the problem and it seems that the error was in a bad configuration of ALERTA. The specific API error was:
403 [POLICY] Alert environment must be one of Production, Development

adding the variable ALLOWED_ENVIRONMENTS in /etc/alertad.conf
ALLOWED_ENVIRONMENTS=['Production','Development']

everything seems to be working fine.

Thanks for your time,

**Comment by massimocandela** [comment]
Thanks a lot!!
I'm going to add this to the documentation for future reference!

Ciao,
Massimo
