### ISSUE TITLE
Current version: undefined new version: 1.19.1. 

### ISSUE THREAD

**Issue by benjaminwaas** [nttgin/BGPalerter#18]
Hi,

I downloaden the newest build. But it shows this message after running:

Current version: undefined new version: 1.19.1. 

best regards,
Benjamin

**Comment by massimocandela** [comment]
Thanks for reporting, I'm investigating.

**Comment by massimocandela** [comment]
I can reproduce the issue, but it doesn't interfere with the normal monitoring.
Somehow the version is lost in the binary and it prompts to you that there is a newer version online.

I'm going to deploy soon a fix. Anyway the monitoring is not affected.

**Comment by massimocandela** [comment]
Fixed in: https://github.com/nttgin/BGPalerter/releases/tag/v1.19.2
Let me know and thanks again for reporting it.

**Comment by benjaminwaas** [comment]
Thanks for the quick response! I tested this version and can report that the issue has been solved :)

**Comment by massimocandela** [comment]
Good! 👍
