### ISSUE TITLE
add proxy support to connectorRIS

### ISSUE THREAD

**Issue by nimrodl** [nttgin/BGPalerter#19]
It may be required to run in an environment without direct access to the internet. The Websocket library suggests that this is possible 
https://github.com/websockets/ws#how-to-connect-via-a-proxy

using https-proxy-agent available here
https://github.com/TooTallNate/node-https-proxy-agent

It may also be useful to support proxy of other connections like those used by generate to download prefixes from RIPEstat.

**Comment by massimocandela** [comment]
This has been solved by https://github.com/nttgin/BGPalerter/pull/234
Big thanks to @fdomain
