### ISSUE TITLE
how to turn off visibility alerts?

### ISSUE THREAD

**Issue by randyqx** [nttgin/BGPalerter#20]
a bunch of (sub)- prefixes are beacons which are announced and withdrawn.  how can i suppress visibility alerts for them?

**Comment by massimocandela** [comment]
Hi Randy, for now you cannot suppress only a specific kind of monitoring (e.g. the visibility one) on a prefix. But you can suppress all of them by setting ignore:true on the sub-prefixes (so you monitor the prefix and suppress the specific sub-prefix). Indeed this is a great limitation I will fix asap. Thanks for reporting this use case.

**Comment by randyqx** [comment]
hi massimo.  i suspect few folk have beacons, so is likely not a widespread use case.  we just happen to have a project going with a lot of them.  i muted the slack channel :)

**Comment by massimocandela** [comment]
Hi Randy, this should be done. Documented [here](https://github.com/nttgin/BGPalerter/blob/master/docs/prefixes.md#prefixes-fields). For now it's available only if you run the source code. The binaries will come soon.

**Comment by massimocandela** [comment]
Released in https://github.com/nttgin/BGPalerter/releases/tag/v1.20.0 (including binaries).
