### ISSUE TITLE
Tutorial about BGPalerter and Alerta

### ISSUE THREAD

**Issue by massimocandela** [nttgin/BGPalerter#213]
I think it would be useful to have a step-by-step tutorial (in the documentation) about how to install and integrate Alerta with BGPalerter.

Who can help with this? @mirceaulinic ?

**Comment by mirceaulinic** [comment]
Sure thing, happy to. Could you please show me an example of what's expected (roughly) to include? Is there a similar tutorial for another integration?

**Comment by massimocandela** [comment]
Hey @mirceaulinic,

First of all, I hope everything is good with you!
This is going to be the first tutorial (probably more will come). I thought that the Alerta integration can be extremely interesting for users who have no other log storage system in place and would like a complete monitoring, including UI.

I was thinking something step by step, including:
* how to install Alerta
* hot to properly configure it for a generic and secure case (including configuration checks like https://github.com/nttgin/BGPalerter/issues/161)
* what to change in config.yml to enable BGPalerter to Alerta

Something that could be almost "copy and paste" for the user.

Whenever you have time. Thanks a lot, much appreciated!
