### ISSUE TITLE
Time on alert is not on 24 hour format

### ISSUE THREAD

**Issue by aalmenar** [nttgin/BGPalerter#228]
**Describe the bug**
Time on the alert is incorrect

**Expected behavior**
Message says:

When event started:   2020-05-02 03:08:29 UTC
Last event:           2020-05-02 03:09:24 UTC

When it should be (It says 03:08:29 when in fact its 15:08:29):

When event started:   2020-05-02 15:08:29 UTC
Last event:           2020-05-02 15:09:24 UTC

**Are you using the binary or the source code?**
Binary

**Your information**
The prefix XXXX has been withdrawn. It is no longer visible from 10 peers
DETAILS:
------------------------------------------------------
Monitored prefix:     XXXX
Prefix Description:   XXXX
Prefix origin:        XXXX
Event type:           withdrawal-detection
When event started:   2020-05-02 03:08:29 UTC
Last event:           2020-05-02 03:09:24 UTC
Detected by peers:    10

**Comment by massimocandela** [comment]
Thanks for reporting.

I'm able to reproduce it. It happens with reportEmail, the email template truncates AM/PM. 
As suggested by you, I will convert the dates to 24 hours format.
