### ISSUE TITLE
error: Slack reporting is not enabled: no group is defined

### ISSUE THREAD

**Issue by stahr** [nttgin/BGPalerter#24]
Is this a group which must be defined in within Slack or is something missing from config.yml?  

  - file: reportSlack
    channels:
      - hijack
      - newprefix
      - visibility
      - path
    params:
      colors:
        hijack: '#d60b1c'
        newprefix: '#fa9548'
        visibility: '#fad648'
        path: '#42cbf5'
      hooks: https://hooks.slack.com/services/AAAA/BBBB/CCCC

The webhook URL should work - I took it from when I was experimenting with the NLNOG/bgpalerter project.  Changing the URL to something invalid gives me the same error which is why there is something missing from the default config.yml which specifies the "group".

**Comment by massimocandela** [comment]
Please, see https://github.com/nttgin/BGPalerter/blob/master/config.yml.example
under hooks you have to define groups, among which at least a "default" one

**Comment by stahr** [comment]
I could swear that I tried that, but obviously I didn't because this time it worked.  Thanks!
