### ISSUE TITLE
Documentation? Specifically docker

### ISSUE THREAD

**Issue by mattfaraday** [nttgin/BGPalerter#247]
**Describe what you would like to achieve**

I want to run BGPalerter in docker, but there's no information on here or on hub.docker.com that would tell you how to launch it. What ports to expose ? Does it require a volume ? Are there environment variables set ??

**Describe why the current solution (if any) is not satisfactory**

There's literally no information at all.

Could we see an example docker-compose file maybe that would easily show us all required info.

**Comment by massimocandela** [comment]
I added a sentence in the documentation, but indeed the documentation for Docker needs improvement. Especially when you enable options like the uptimeApi which requires port 80 open (but it's not enabled by default). Or if you want to store alerts on file, where a volume would be useful.

I will improve it, but please, feel free to contribute!

**Comment by massimocandela** [comment]
Ok, thanks. Remember to use `nttgin/bgpalerter:dev` and not `latest`
