### ISSUE TITLE
Hijack alerts should be show full as-path

### ISSUE THREAD

**Issue by nimrodl** [nttgin/BGPalerter#26]
Hijack alerts should display complete as-path for hijacked prefixes. Paths from all peers observing the hijack should be displayed in the alert.

A knob to set a minimum threshold of peers observing the hijack would also be nice.

**Comment by massimocandela** [comment]
Paths from all peers, means 600+ paths. I have to think a way to summarise such information (maybe send it only by email).

The minimum peers threshold is already available (recently added for monitorHijack and monitorNewPrefix, available in the source, it will in the binary with the next release) https://github.com/nttgin/BGPalerter/blob/master/docs/configuration.md#monitors

**Comment by massimocandela** [comment]
Feature introduced in 8fd3c2ef95800f208f0fbdb2179e2569b42f6961 will go out with the next release.
In the config file it's possible to configure the top X most common paths to show. The paths will be reported in the email.

**Comment by massimocandela** [comment]
Released in [v1.21.0](https://github.com/nttgin/BGPalerter/releases/tag/v1.21.0)
