### ISSUE TITLE
add support for prefix list as input to 'generate' command

### ISSUE THREAD

**Issue by nusenu** [nttgin/BGPalerter#28]
Currently you can provide an ASN (`-a`) as input to the `generate` command to generate the list of prefixes to monitor.

It would be nice to support an input file (`-p`) containing one prefix per line that generates the `prefixes.yml` output file.
It must be an input file (not a parameter like `-e`) since the list of prefixes would be to long to be passed in on the command line.

The ASN would be determined by:
- RPKI ROA
- if there is no ROA use IRR
- if there is no ROA or IRR entry: use currently announcing ASN as per RIPEstat

**Comment by massimocandela** [comment]
Solved in https://github.com/nttgin/BGPalerter/commit/f33bd4b4e6f4cc120898d83a4fda64123b072109
Will go out with next release.

**Comment by nusenu** [comment]
thanks a lot, looking forward to make use of this!

**Comment by massimocandela** [comment]
Released in [v1.21.0](https://github.com/nttgin/BGPalerter/releases/tag/v1.21.0)
