### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by OeveringIT** [nttgin/BGPalerter#3]
Hi,

So I've downloaded the bin and run it but I get three errors
>error: hijack template cannot be loaded
>error: newprefix template cannot be loaded
>error: visibility template cannot be loaded

What I did:
>cd /appl/bgpalerter
>wget https://raw.githubusercontent.com/nttgin/BGPalerter/master/bin/bgpalerter-linux-x64
>wget https://raw.githubusercontent.com/nttgin/BGPalerter/master/config.yml
>wget https://raw.githubusercontent.com/nttgin/BGPalerter/master/prefixes.yml
>chmod +x bgpalerter-linux-x64
>nano config.yml
>nano prefixes.yml
>./bgpalerter-linux-x64

Outcome:
>./bgpalerter-linux-x64
>loading config: /appl/bgpalerter/config.yml
>RUNNING ENVIRONMENT: production
>Subscribing to: output removed
>loading config: /appl/bgpalerter/config.yml
>RUNNING ENVIRONMENT: production
>error: hijack template cannot be loaded
>error: newprefix template cannot be loaded
>error: visibility template cannot be loaded

Did I do something wrong?

Thanks!

**Comment by massimocandela** [comment]
Hi, 
it looks like you enabled the email reporting (commented in config.yml).
You have to download also `reports/email_templates`.

Indeed this was not documented in the README, I just added a line for it.

Thanks for reporting!
