### ISSUE TITLE
Don't add channel "software-update" as default for all reports

### ISSUE THREAD

**Issue by rybnico** [nttgin/BGPalerter#309]
If `checkForUpdatesAtBoot` is set to `true`, notifications about new versions will be sent to all configured "reports", regardless of the channels configured.

The channel `software-update` is added to all reports here: https://github.com/nttgin/BGPalerter/blob/b33e47a055f1ff59491ac09b76b05c67cabf784c/src/env.js#L247

My suggestion is to either make `software-update` a non-default channel (and add it to default-config/examples/release notes) or to add a new config switch `addUpdatesChannelToAllReports` which defaults to `true` to keep the current behaviour.

We have 2 reports defined of which one triggers alerts for the person on-call. It wouldn't be nice to wake them up in the middle of the night just because a new version of BGPalerter was released... 

I can submit a PR if you decide for one of the options mentioned above.

**Comment by massimocandela** [comment]
Hi @rybnico,

Software updates notification are only sent to the default user group ([documented here](https://github.com/nttgin/BGPalerter/blob/master/docs/usergroups.md)).
The default user group is more an "admin" group. I think the noc and 24/7 should have a dedicated group.

Let me know if this solution is good for you.

**Comment by rybnico** [comment]
Hi @massimocandela,
thanks for your super fast response!

I didn't saw this:
> Note that the default group is used also for administrative and error communications.

Yes, using groups works for us! I close the issue then.

**Comment by massimocandela** [comment]
I think indeed it was not clear. I added a few lines explaining this directly in the section talking about reports.

I'll think a way to add the possibility to create a group in the auto-configuration step. Maybe I can ask in that phase if the user wants to create another user group.

Thanks for the feedback.
