### ISSUE TITLE
Toggle upgrade "alerts" or have them sent another way. 

### ISSUE THREAD

**Issue by mattfaraday** [nttgin/BGPalerter#327]
**Describe what you would like to achieve**

I would like to either be able to turn off the "software-update" alert, or move them to somewhere else (e.g. email)

**Describe why the current solution (if any) is not satisfactory**
In our setup, alerts are sent and engineers must act upon any alerts recieved. For example, if any BGP routes are hijacked or announced incorrectly etc. To that end, we have setup systems to automatically SMS or call engineers based on alerts recieved including those from BGPAlerter. However, when we get software update alerts they are announced in the same channel as all the other alerts. 

I would like to either be able to send non-critical alerts like this to a different destination (e.g. don't alert in slack, but do send an email?) or to be able to toggle these particular alerts on/off. I haven't seen a configuration option for this. 

**Provide an example**

"A new version of BGPalerter is available. Current version: 1.25.0 new version: 1.26.2 Please go to https://github.com/nttgin/BGPalerter"

This message is then sent (in our case) to our slack alerts channel. Messages here will cause engineers to be notified of a problem and to investigate.

**Comment by massimocandela** [comment]
Hello @mattfaraday,

There was in the past anothe ticket with the same request: https://github.com/nttgin/BGPalerter/issues/309
> In short, you should never use the admin user group to send alert to the noc but create a specific user group.

Since this created already some question, I will make sure to make this obvious or to prompt for the creation of a user group during setup.

Ciao,
Massimo

**Comment by mattfaraday** [comment]
Hi

Thanks for the super quick reply! 
That's great thanks, looks like I can easily setup a group for the hijack/visibility ones

Thank you!!
