### ISSUE TITLE
Option to trigger test alert

### ISSUE THREAD

**Issue by darkblaze69** [nttgin/BGPalerter#340]
Feature request:
Trigger a test alert for testing all report modules (mis)configuration.
Didn't find out how to do this.

**Comment by massimocandela** [comment]
Hi @darkblaze69,

There is the option -t [documented here](https://github.com/nttgin/BGPalerter/blob/dev/docs/installation.md#bgpalerter-parameters). Unfortunately, it is still in the `dev` branch and it will go into the next release.
If you are using the source code, you can already do it by switching to the dev branch.
