### ISSUE TITLE
Separate paths by comma instead of semicolon

### ISSUE THREAD

**Issue by lspgn** [nttgin/BGPalerter#349]
**Describe what you would like to achieve**
When multiple paths are listed for a prefix, they are separated by a semicolon:
```
{
  "paths": "[51786,51786,51786,39533,6762,5511,45903,13335];[6939,45903,13335]"
}
```
It would be better to have them separated by a comma character`,`.

**Describe why the current solution (if any) is not satisfactory**
When rendering a JSON template:
```'{"paths":"${paths}"}```
I need to render the list of paths as a string. Which can complicate post-processing.
If it was separated by comma, the engine could render an array of arrays.
```'{"paths":[${paths}]}```
```
{
  "paths": [
    [
      51786,
      51786,
      51786,
      39533,
      6762,
      5511,
      45903,
      13335
    ],
    [
      6939,
      45903,
      13335
    ]
  ]
}
```

Thank you :)

**Your information**
AS13335

**Comment by massimocandela** [comment]
done!
