### ISSUE TITLE
Generating prefixes.yml is empty

### ISSUE THREAD

**Issue by mirosgold** [nttgin/BGPalerter#353]
Hi,
I've tried using npm and binary and both creates a prefixes.yml with {} inside.
Any idea?

**Comment by massimocandela** [comment]
Hi @mirosgold,

I'm aware of this. Currently RIPE is experiencing issues with their APIs. 
They are already working on solving the problem. Everything should come back to normal soon.

The next release of BGPalerter will be less sensitive to malfunctions of RIPEstat APIs.
If you are using the source code, checkout the dev branch and use the options --H while generating the prefixes.

**Comment by mirosgold** [comment]
Thanks, will try.

**Comment by massimocandela** [comment]
At the moment it looks like all APIs are answering empty sets. So -H will not help :(

**Comment by massimocandela** [comment]
I just pushed in `dev` some changes that will make the generation of prefixes more robust (but maybe incomplete in case of RIPEstat failure).

I will investigate further ways to reduce BGPalerter's dependency on RIPEstat for the generation of the initial configuration.

**Comment by massimocandela** [comment]
RIPEstat service announcement https://www.ripe.net/support/service-announcements/delay-in-ripestat-routing-data/
