### ISSUE TITLE
compare yaml configuration with rpki before alerting hijacks

### ISSUE THREAD

**Issue by Nenq** [nttgin/BGPalerter#358]
**Describe the bug**
A hijack alert is being triggered even though, valid RoA is available.

**Provide an example**
In this [screenshot](https://pics.host1plus.com/images/2020/10/05/ecd39eb13c6cea4ad6c4139094d88786.png)  you can see a prefix and a BGP message. The prefix has a RoA record for both ASNs.

**Expected behavior**
Hijack alert should be triggered only when there's no RoA record for the ASN from which is being announced. 

**Are you using the binary or the source code?**
Binary

**Your information**
AS61317

**Comment by massimocandela** [comment]
Hi Nenq,

According to which definition "Hijack alert should be triggered only when there's no RoA record for the ASN from which is being announced" ? 
Having a ROA doesn't prevent hijacks everywhere in the network. You receiving that alert is -proof- that somebody accepted the hijacked route as best_path and propagated it.

**Comment by Nenq** [comment]
Hello,

I am aware of adding multiple ASNs, however, it requires some manual work if you want to add additional ASN every other day.

Anyways, having a rpki check before sending a hijack alert would be nice!

Thank you for the amazing tool!

**Comment by massimocandela** [comment]
Done, it will be in the next release.
