### ISSUE TITLE
Question: High Availablity / Multiple Instances

### ISSUE THREAD

**Issue by benyanke** [nttgin/BGPalerter#378]
Does BGPalerter support running multiple replicas with the same config and volume to more easily facilitate things like no-downtime rolling restarts and config changes, or does it only support one replica?

**Comment by massimocandela** [comment]
Hi @benyanke,

You can share the same config but not the same volume if you have persistStatus on (in that case the volume can be re-used but not written at the same time by multiple instances).
Changes to prefixes.yml are auto reloaded without restarts.
