### ISSUE TITLE
Path email template - more details

### ISSUE THREAD

**Issue by gawul** [nttgin/BGPalerter#389]
**Describe what you would like to achieve**
I would like to see the path change email template/body contain more details - including the time, prefix, path that triggered the alert and the match criteria

**Describe why the current solution (if any) is not satisfactory**
While the message from the monitored prefix can be customized, the specifics are not available

**Provide an example**
The current template only contains ${summary}

Add the following - similar to other templates

```
DETAILS:
------------------------------------------------------
Event type:           ${type}
Last event:           ${latest} UTC
Triggering AS path:   ${paths}
```

**Your information**
Andy Koch AS393841

**Comment by TheBlueMatt** [comment]
Agreed that would be a nice template upgrade, but note that you can do this manually now - whatever directory bgpalerter starts from it should create a file called `src/reports/email_templates/path.txt` which you can edit and on restarting bgpalerter it will start using the contents there.

**Comment by massimocandela** [comment]
Hi @gawul,

I added a default template similar to what you suggest, it will go out with the next release.

As also suggested by @TheBlueMatt, you can define your own templates. The documentation is [here](https://github.com/nttgin/BGPalerter/blob/master/docs/context.md).

Thanks for the suggestion
