### ISSUE TITLE
Report module for MS Teams

### ISSUE THREAD

**Issue by netwninja** [nttgin/BGPalerter#430]
**Describe what you would like to achieve**
To have a feature to send an alert to MSteams just like SLACK using WEBHOOK.

**Describe why the current solution (if any) is not satisfactory**
Not every Organisation using SLACK.

**Provide an example**
Provide an example in terms of prefixes and BGP messages. Possibly provide a snippet of config.yml and prefixes.yml.

```
#  - file: reportMSteams
#    channels:
#      - hijack
#      - newprefix
#      - visibility
#      - path
#      - misconfiguration
#      - rpki
#    params:
#      showPaths: 0 # Amount of AS_PATHs to report in the alert
#      colors:
#        hijack: '#d60b1c'
#        newprefix: '#fa9548'
#        visibility: '#fad648'
#        path: '#42cbf5'
#        rpki: '#d892f0'
#      hooks:
#        default: _YOUR_MSTEAMS_WEBHOOK_URL_


```

**Your information**
Gaurav Sood/Western Digital

**Comment by massimocandela** [comment]
Hi @netwninja,

This is already available, see [here](https://github.com/nttgin/BGPalerter/blob/master/docs/report-http.md#ms-teams).
Let me know if you find any issue while configuring it.

**Comment by netwninja** [comment]
> Hi @netwninja,
> 
> This is already available, see [here](https://github.com/nttgin/BGPalerter/blob/master/docs/report-http.md#ms-teams).
> Let me know if you find any issue while configuring it.

Thank you, Massimo. Much appreciated.
