### ISSUE TITLE
To enable reportHTTP reporter for Workplace

### ISSUE THREAD

**Issue by deepuad** [nttgin/BGPalerter#431]
**Describe what you would like to achieve**
To achieve enabling reportHTTP alerts to Workplace API using HTTP Webhook.
 
**Describe why the current solution (if any) is not satisfactory**
As we are using Workplace ( Work chat Alerts ) for all other applications in a network. It would be highly appreciated if you could help us in enabling reportHTTP alerts to Workplace.  

**Provide an example**
Below is the reportHTTP configuration configured in the config.yml file.

 - file: reportHTTP
   channels:
     - hijack
     - newprefix
     - visibility
     - path
     - misconfiguration
     - rpki
   params:
     templates: # See here how to write a template https://github.com/nttgin/BGPalerter/blob/master/docs/context.md
       default: '{"text": "${summary}"}'
     headers:
     isTemplateJSON: true
     showPaths: 5 # Amount of AS_PATHs to report in the alert
     hooks:
       default: http://X.X.X.X/fbtestProj/nmsalertapi?key=XXXX&grpName=Test+romit&subGrpName=Test+romit&alertMsg=test

**Your information**
Dileep AS: 24309

**Comment by massimocandela** [comment]
Hi @deepuad,

What is the problem? Do you get any error? 
Did you try to modify one of [these examples](https://github.com/nttgin/BGPalerter/blob/master/docs/report-http.md).
Please, use version 1.27.0 where reportHTTP error logs have been improved.

If you find a working example, please share it so we can add it to the page with the examples.

**Comment by deepuad** [comment]
Hi @massimocandela,

Okay, Let me check with 1.27.0 and update.

Thanks

**Comment by deepuad** [comment]
Sir, getting a syntax error attached, please suggest.

![image](https://user-images.githubusercontent.com/65802763/102216755-a030c500-3f01-11eb-83c0-383826e55c48.png)

**Comment by massimocandela** [comment]
The template you created is not a valid JSON, in particular it starts with "+". If it was supposed to be a JSON you have to fix it. Otherwise set isTemplateJSON to false. There are validators [online](https://www.jsonschemavalidator.net/). If you don't suceed in fixing it, share the template here (use the "insert code" function).

**Comment by deepuad** [comment]
Hi Sir,

TemplateJSON set to false.

This time I didn't get any error but, alerts are getting in the workplace.
Sir, please help me in understanding below is the configuration

file: reportHTTP
channels
hijack
newprefix
visibility
path
misconfiguration
rpki
params:
templates: # See here how to write a template https://github.com/nttgin/BGPalerter/blob/master/docs/context.md
default: '{"text": "${summary}"}'
headers:
isTemplateJSON: false
showPaths: 5 # Amount of AS_PATHs to report in the alert
hooks:
default: http://<IPAd>/fbtestProj/nmsalertapi?key=XXXX&grpName=Test+romit&subGrpName=Test+romit&alertMsg=test

**Comment by deepuad** [comment]
Getting error "Status failed status 400"
**config.yml**

  - file: reportHTTP
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
    params:
      templates: # See here how to write a template https://github.com/nttgin/BGPalerter/blob/master/docs/context.md
        default: '{"text": "${summary}"}'
      headers:
      isTemplateJSON: true
      showPaths: 5 # Amount of AS_PATHs to report in the alert
      hooks:
        default: https://10.100.109.55/fbtestProj/nmsalertapi?key=NHRKSGNMSRRS&grpName=Test+romit&subGrpName=Test+romit&alertMsg=Testing ${summary}
        noc: _YOUR_WEBHOOK_URL_

**tested:** 

./bgpalerter-linux-x64 -t

**error-2020-12-16.log** 

tail -f error-2020-12-16.log 
2020-12-16T14:22:17+00:00 error: Error: Request failed with status code 400
2020-12-16T14:22:17+00:00 error: Error: Request failed with status code 400
2020-12-16T14:22:17+00:00 error: Error: Request failed with status code 400
2020-12-16T14:22:17+00:00 error: Error: Request failed with status code 400
2020-12-16T14:22:17+00:00 error: Error: Request failed with status code 400


Thankyou

**Comment by massimocandela** [comment]
Hi @deepuad,

Template variables can be used only in templates.
Try removing `${summary}` from `default: https://10.100.109.55/fbtestProj/nmsalertapi?key=NHRKSGNMSRRS&grpName=Test+romit&subGrpName=Test+romit&alertMsg=Testing ${summary}`.

Additionally, you should read the format of the message accepted by the server. Are you sure it is simply `'{"text": "${summary}"}'` ? (error 400 is Bad request)

**Comment by deepuad** [comment]
Yes,  Sir, I have removed ${summary} from webhook and tested with the below urls:

default: https://10.100.109.55/fbtestProj/nmsalertapi?key=NHRKSGNMSRRS&grpName=Test+romit&subGrpName=Test+romit&alertMsg=Testing.

&

**default: https://10.100.109.55/fbtestProj/nmsalertapi?key=NHRKSGNMSRRS&grpName=Test+romit&subGrpName=Test+romit&alertMsg=**

With the above URLs, we are not getting 400 errors but still, alerts are not working.

>> We are using the below same URL in the Network Monitoring Tool, where it is working as expected.

http://X.X.X.X/fbtestProj/nmsalertapi?key=NHRKSGNMSRRS&grpName=HYD_CORE_TRAFFIC_DIP&subGrpName=HYD_CORE_TRAFFIC_DIP&alertMsg=Dip in Traffic:Rx ${InPercentUtil}% utilization on ${Caption} in ${Node.Caption} on ${N=Generic;M=DateTime;F=DateTime}.

**Comment by massimocandela** [comment]
BGPalerter sends a JSON body on the POST request containing the template you specified (so, the alert is in the body, not in the URL).  Once the alerts are reaching your server you have to check what configuration you have there and if you are correctly authenticated.  Sorry, this is not a problem with BGPalerter, there is nothing I can do.

**Comment by deepuad** [comment]
Ok thank you for confirming.
