### ISSUE TITLE
Unable to receive alerts on Telegram bot with Updated version 1.27.0 where it is working fine with 1.26.0

### ISSUE THREAD

**Issue by deepuad** [nttgin/BGPalerter#432]
**Describe the bug**
  reportTelegram alerts are not working with an updated version: 1.27.0

**Provide an example**
-file: reportTelegram
   channels:
     - hijack
     - newprefix
     - visibility
     - path
     - misconfiguration
     - rpki
   params:
     showPaths: 5 # Amount of AS_PATHs to report in the alert
     botUrl: https://api.telegram.org/botXXXXXXX:AAE4pj84CHZ67Dc2nFSVzkphx-A4B3FdWoQ/sendMessage
     chatIds:
       default: -XXXXXXXXXXX

**Are you using the binary or the source code?**
 Using Binary

**Your information**
Dileep ASN: 24309

**Comment by massimocandela** [comment]
Hi @deepuad,

Version 1.27.0 sets two default groups `default` and `noc` during auto configuration.
If you started the auto-configuration with 1.27.0 but used an old config.yml, it could be you don't have the right user group set. If that is the case, try to add a line `noc: -XXXXX` in your reportTelefgram configuration

**Comment by massimocandela** [comment]
I added a fix that allows reportTelegram to use the default user group if the user group specified in prefixes.yml is not available. It is currently in dev. In the meanwhile set the proper user group as in my previous comment.
Thanks for reporting.

**Comment by deepuad** [comment]
Issue resolved.

Thankyou Sir.

**Comment by deepuad** [comment]
Resolved.

Thankyou Sir.
