### ISSUE TITLE
pidFile config results in error with 1.27.0

### ISSUE THREAD

**Issue by ccaputo** [nttgin/BGPalerter#447]
**Describe the bug**
pidFile config results in the following error with 1.27.0:

```
error: Cannot write pid file: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (#####)
```

This did not happen with 1.26.2 with the same config file.

Commenting out pidFile makes the error go away, albeit with a loss of a useful pidfile.

We use a pidFile with a full pathname.  With and without quotes the error happens.

**Are you using the binary or the source code?**
Source.

**Comment by massimocandela** [comment]
Hi @ccaputo,

what's the OS? Thanks for reporting.

**Comment by massimocandela** [comment]
This should be fixed in release. Please, try to run the source code from the `release` branch and tell me if it works also for you. Thanks
