### ISSUE TITLE
How to automatically update prefixes for specific ASNs

### ISSUE THREAD

**Issue by mmarin11** [nttgin/BGPalerter#482]
Hi BGPalerter community.

I would like to monitor prefixes of downstream ASNs and I was wondering if there is a way to automatically update prefixes (prefixes.yml file) for specific ASNs. Is there a way to update prefixes via crontab?

**Comment by massimocandela** [comment]
Hi @mmarin11,

You can doo two things:
* set in config.yml the number of days for generating the prefixes in `generatePrefixListEveryDays`
* use the [generate](https://github.com/nttgin/BGPalerter/blob/master/docs/prefixes.md#generate) command line option with crontab

If you are monitoring multiple ASes and you want to update only one of them, you can create and configure multiple prefixe files and update only one.

**Comment by mmarin11** [comment]
This is great
Thanks Massimo.

**Comment by mmarin11** [comment]
Hi Massimo. Sorry to bother you.

I configured the generatePrefixListEveryDays paramater in config.yml however it does not seem to be working. If I add a new ASN under the option: section in prefixes.yml it does not seem to update the prefixes that are advertised by the specified ASN. I'm not sure if there is something missing or wrong in the config.

I would appreciate your support




![image](https://user-images.githubusercontent.com/40378669/109098102-e498c800-76dd-11eb-97c5-4768775112dc.png)

**Comment by massimocandela** [comment]
Hello @mmarin11,

The generatePrefixListEveryDays option works only if you auto generate the prefixes the first time.
If you manually edit prefixes.yaml the option will not work.

I will add better documentation for it.

Ciao,
Massimo

**Comment by mmarin11** [comment]
Thank you
