### ISSUE TITLE
Help Understanding FullThrottle Code

### ISSUE THREAD

**Issue by rnikoopour** [nttgin/BGPalerter#497]
Hello,

I'm trying to understand the purpose of the calls to `this.updates.foreach` in `_startStream`

https://github.com/nttgin/BGPalerter/blob/dfacb37ba6f87c11080a5bf3ffd9dc41c20e4030/src/connectors/connectorFullThrottle.js#L121-L134

Why is it called 10 times in a row?

**Comment by massimocandela** [comment]
Hello @rnikoopour, 

You are looking at a piece of code that is used for stress tests and that is not part of the normal BGPalerter.
That connector generates an absurd amount of fake bgp data. It is useful during development to test memory leaks, cpu performance, thresholds, etc...

There is also another connector used during automated tests that is called ConnectorTest. Real connectors are instead ConnectorRIS and ConnectorSwUpdates.

Just out of curiosity, what are you doing with it?
