### ISSUE TITLE
No alert on withdraw of a more-specific

### ISSUE THREAD

**Issue by kage709** [nttgin/BGPalerter#516]
Hello

thanks for this amazing program. I thought about writing something like this myself and then found bgpalerter being mentioned in the nanog mailing list.

**Describe the bug**
There is no alert for a withdraw of a more-specific route.

**Provide an example**
Let's assume the prefix 5.5.0.0/20 is always in the DFZ.
Announce 5.5.1.0/24: bgpalerter will report in logs/reports.log "AS42275 is announcing..."
Withdraw 5.5.1.0/24: bgpalerter will log nothing in log/reports.log

**Expected behavior**
bgpalerter should log something when a withdraw happens.

**Are you using the binary or the source code?**
v1.27.1 Binary
Here's the config file:
```
cat prefixes.yml
```
```
options:
  monitorASns:
    '42275':
      group: noc
```

**Your information**
AS42275

best regards
Karl

**Comment by massimocandela** [comment]
Dear @kage709,

Your config file is not correct. According to your config file you are monitoring the AS42275 and you are NOT expecting any prefix to be announced.

prefixes.yml must contain the list of prefixes that you are supposed to announce and monitor. You are receiving the warning when the prefix is announced exactly for this reason: according to your configuration you were not supposed to see that prefix. When the prefix is no longer visible, the correct condition is back and so there is no reason to generate any alert.

Please, read the documentation on how to [generate prefixes.yml correctly](https://github.com/nttgin/BGPalerter/blob/master/docs/prefixes.md#generate). If you find this not clear, I will make sure to improve the documentation.

**Comment by kage709** [comment]
Thank you very much for your kind explanation.

Let's suppose we have a /20 announced and it is listed in prefixes.yml. Due to a misconfiguration a more-specific /24 is announced. This /24 is not in prefixes.yml because we're usually only announcing a /20. In that case, bgpalerter will alert upon announce of the /24 but not alert upon withdraw of the /24. Do I understand that correctly?

That means that bgpalerter will not inform us when the misconfiguration has been fixed. If that is the case maybe you could be so kind and turn this ticket into a feature-request. It would be really great if bgpalerter could also write something into the logs when the error-state is over (like, say, Nagios can be configured to send an e-mail when a "Recovery" event happens).

Again, thank you very much for your time and for maintaining this amazing tool!

**Comment by massimocandela** [comment]
Hi @kage709,

> Let's suppose we have a /20 announced and it is listed in prefixes.yml. Due to a misconfiguration a more-specific /24 is announced. This /24 is not in prefixes.yml because we're usually only announcing a /20. In that case, bgpalerter will alert upon announce of the /24 but not alert upon withdraw of the /24. Do I understand that correctly?

Yes

> That means that bgpalerter will not inform us when the misconfiguration has been fixed. If that is the case maybe you could be so kind and turn this ticket into a feature-request. It would be really great if bgpalerter could also write something into the logs when the error-state is over (like, say, Nagios can be configured to send an e-mail when a "Recovery" event happens).

There are similar requests among the tickets in this repo. What you are asking sounds easy but it's not.
What BGPalerter does is to analyze a lot of BGP updates coming from a large number of peers (600+). However, it does not have a total visibility on the entire Internet (nothing in this world has) or the certainty that those peers are always up. This means that we can be sure when something happens, but we cannot be sure if something does not.
I'll let you know if I can implement an acceptable compromise.
