### ISSUE TITLE
Regenerate Prefix List & Maintain Specific Configuration

### ISSUE THREAD

**Issue by telescope40** [nttgin/BGPalerter#518]
Currently Evaluating bgpalerter for my organization.
I was interested in re-generating the prefix list on a daily/weekly to update our announcements without manual intervention and log the files to an internal git repo. 
When the prefix list regenerates it removes the specific path monitoring I set up. 

I would expect the solution is to either 
1. Turn off the automatic prefix regeneration , wait for the alert for new prefix announcements and manually add.
2. Enable a cron to re-add the specific path monitoring 
3. Can I add the specific path monitoring into the config.yaml file? 

Louis D / Webair

**Comment by massimocandela** [comment]
Hi @telescope40,

Path monitoring configs should not disappear during auto-regeneration of prefixes.yml.
I consider this a bug. I didn't have time to reproduce it yet, but I think I know why this is happening.

Thanks for reporting!

**Comment by massimocandela** [comment]
Fixed, it will go out with the next release.

**Comment by massimocandela** [comment]
This has been released.
