### ISSUE TITLE
Bootstrap current BGP state from a dump, report mis-originates from ground state before update feed

### ISSUE THREAD

**Issue by ggm-at-apnic** [nttgin/BGPalerter#527]
I'd like to see a report of mis-announces from a BGP dump, as well as from the update feed. 

It looks like the bgpalerter uses some other source to establish initial ground truth for the autoconfig from BGP, but won't report on mis-originations in BGP before an announce or withdraw is seen.

**Comment by ggm-at-apnic** [comment]
On 31 Mar 2021, at 3:08 am, Massimo Candela ***@***.******@***.***>> wrote:



Hi @ggm-at-apnic<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fggm-at-apnic&data=04%7C01%7C%7C2d46693c8124494e7cf308d8f39e67bc%7C127d8d0d7ccf473dab096e44ad752ded%7C0%7C0%7C637527209003128852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dibUFKPaO%2F3iZ2lk3c9%2B37exUKRgGJe9aYkzjIEc0W8%3D&reserved=0>,

BGPalerter uses current visibility + RPKI to create a "snapshot" of the initial state, persisted in prefixes.yml.
This is just to simplify the installation, but the file prefixes.yml can be created manually or with any other script.
In this context, the ground truth is whatever prefixes.yml (+rpki) says.

Based on the information above, what do you mean with "report on mis-originations in BGP before an announce or withdraw is seen"? Would you like to feed historical updates to BGPalerter based on a MRT file?
Keep in mind that the ground truth is prefixes.yml. To really make BGPalerter work historically on mis-originations, you need to recreate the entire context (e.g., historical RPKI vrps files). Ofc, it would be possible to do analyses of other kind or to accept a certain amount of inaccuracy. Would that be acceptable? Did I understand the request?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnttgin%2FBGPalerter%2Fissues%2F527%23issuecomment-810429602&data=04%7C01%7C%7C2d46693c8124494e7cf308d8f39e67bc%7C127d8d0d7ccf473dab096e44ad752ded%7C0%7C0%7C637527209003128852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Wq%2F7CTIXKohxC5xeFP%2BidwuXKNpcG3tDZN8YqmYmfrI%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB354SH7SV7RXMYSPUKK6G3TGIAPVANCNFSM42A4S5EQ&data=04%7C01%7C%7C2d46693c8124494e7cf308d8f39e67bc%7C127d8d0d7ccf473dab096e44ad752ded%7C0%7C0%7C637527209003138845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mOl8HL4BoV3%2BHX7VTUT1%2Fx7aZSIjoj5BNXZIhMVqnUs%3D&reserved=0>.

Lets say I want to monitor 203.133.248.0/24 originated by AS4608.

Lets say that I manually create a configuration with this prefix, and as in prefix.yml.

Now, lets also say, that in the interval, somebody starts announcing it from AS1221.

I start BGPalerter. But, the announce from AS1221 is stable: There is no update, or withdraw.

Your system won’t “tell” me its currently bogusly announced: it appears to be tracking updates and withdraw only. So, because it doesn’t reflect on the current state of BGP before it sees update and withdraw it cannot inform me about a bogus origination which is stable.

The first I will know, is when its withdrawn.

-G

**Comment by massimocandela** [comment]
Hi @ggm-at-apnic,

ok, now I get it.
I have some ideas on how what you are asking could be implemented.
If this should be supported in production, it must be without the need for the user to provide a dump or the need for an ad-hoc service.
RIS has an API that we could use, but it has only dumps performed ~2 hours in the past.  This would mean that BGPalerter would be able to realize if the monitoring was off in the last 2 hours, recover a dump of 2 hours ago to do an initial check and report "missed alerts", and resume the monitoring at now(). The updates in the last 2 hours would be lost anyway. This is not an ideal solution, because we may alert the user about something that in the last 2 hours was already solved; anyway, would that be acceptable? (maybe with an option in config.yml)

**Comment by ggm-at-apnic** [comment]
On 31 Mar 2021, at 11:00 am, Massimo Candela ***@***.******@***.***>> wrote:



Hi @ggm-at-apnic<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fggm-at-apnic&data=04%7C01%7C%7C40fc2c801441480f364108d8f3e05c93%7C127d8d0d7ccf473dab096e44ad752ded%7C0%7C0%7C637527492246490384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uEWTS0Y2J8Zca%2Fjw5U3iaqmytn84sWXY2%2BmcEnHDk3o%3D&reserved=0>,

ok, now I get it.
I have some ideas on how what you are asking could be implemented.
If this should be supported in production, it must be without the need for the user to provide a dump or the need for an ad-hoc service.
RIS has an API that we could use, but it has only dumps performed ~2 hours in the past. This would mean that BGPalerter would be able to realize if the monitoring was off in the last 2 hours, recover a dump of 2 hours ago to do an initial check and report "missed alerts", and resume the monitoring at now(). The updates in the last 2 hours would be lost anyway. This is not an ideal solution, because we may alert the user about something that in the last 2 hours was already solved; anyway, would that be acceptable? (maybe with an option in config.yml)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnttgin%2FBGPalerter%2Fissues%2F527%23issuecomment-810675596&data=04%7C01%7C%7C40fc2c801441480f364108d8f3e05c93%7C127d8d0d7ccf473dab096e44ad752ded%7C0%7C0%7C637527492246490384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RXG4Tte0k0J3m6bOLWBUKQX1hUShAdORyZ%2Bez6c20ro%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB354SC6NIZJAMGKMDDZIMTTGJX2FANCNFSM42A4S5EQ&data=04%7C01%7C%7C40fc2c801441480f364108d8f3e05c93%7C127d8d0d7ccf473dab096e44ad752ded%7C0%7C0%7C637527492246500378%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fLq6AqM68XMryNrQkXosuR5%2BJqPW321TeRPFOH%2FktWQ%3D&reserved=0>.

Yes. This would be entirely acceptable.

Do you know a prefix subject to beaconing which is more frequent than the RIPE ones? I would like to use non simulated events in BGP, to “see” how the thing works with a small configuration.

-G

**Comment by massimocandela** [comment]
In the past I enjoyed a lot https://rfd.rg.net/beacons.html but it looks like they are all off atm (I also don't remember the frequency). Maybe @randyqx knows more.

**Comment by massimocandela** [comment]
This is done and it will go out with the next release. For now it is in https://github.com/nttgin/BGPalerter/pull/568

**Comment by massimocandela** [comment]
This has been released.
