### ISSUE TITLE
Include RRC identifiers when detecting withdrawals

### ISSUE THREAD

**Issue by appliedprivacy** [nttgin/BGPalerter#59]
Currently a withdrawn log entry look like this:

> The prefix 2a03:e600:100::/48 (ipv6) has been withdrawn. It is no longer visible from 12 peers.

It does not include any information about where the withdrawals have been observed.

It would be useful for diagnostics to include that information. 
It could look something like that:

> The prefix 2a03:e600:100::/48 (ipv6) has been withdrawn. It is no longer visible from 12 peers: RRCXX (9), RRCYY (3)

**Comment by massimocandela** [comment]
Are you finally interested in the RRCs or the location of the peers? Such us NL (3) IT (2)

**Comment by appliedprivacy** [comment]
I find RRC IDs more useful since there are multiple RRCs in a country and so the RRC ID is more granular.

**Comment by massimocandela** [comment]
The correlation between location of the RRC and the location of the peer is weak. Some RRCs (for sure RRC0, the one producing more data) are multihop. Additionally, not everybody is familiar with the RRC concept.

I'll think what to do. Maybe we can add more information in the email reporting.

In the meanwhile, such information is anyway available in the data object of the alert (e.g. you can connect it to Kafka and get all the single BGP updates).

**Comment by massimocandela** [comment]
I re-open this. I am working on a "similar" solution.
