### ISSUE TITLE
Latest version initial run and auto config error

### ISSUE THREAD

**Issue by CyberBitz** [nttgin/BGPalerter#593]
First time, downloaded and ran with auto setup, I am getting this error:

**Describe the bug**
Initialized the autoconfig and this is the error after it runs

Loaded config: C:\..........\BGPMonitor\config.yml
BGPalerter, version: 1.28.0 environment: production
TypeError: Cannot read property 'length' of null
    at AS.isValid (C:\snapshot\BGPalerter\dist\src\model.js:142:36)
    at new AS (C:\snapshot\BGPalerter\dist\src\model.js:118:14)
    at C:\snapshot\BGPalerter\dist\src\inputs\inputYml.js:161:64
    at Array.map (<anonymous>)
    at _loop (C:\snapshot\BGPalerter\dist\src\inputs\inputYml.js:149:92)
    at C:\snapshot\BGPalerter\dist\src\inputs\inputYml.js:194:24
    at new Promise (<anonymous>)
    at InputYml._loadPrefixes (C:\snapshot\BGPalerter\dist\src\inputs\inputYml.js:109:14)
    at InputYml.loadPrefixes (C:\snapshot\BGPalerter\dist\src\inputs\inputYml.js:79:20)
    at Timeout._onTimeout (C:\snapshot\BGPalerter\dist\src\inputs\input.js:377:11)

**Provide an example**
Provide an example in terms of prefixes and BGP messages. Possibly provide a snippet of config.yml and prefixes.yml.

**Expected behavior**
provide an output that does not result in an error

**Are you using the binary or the source code?**
I downloaded the bgpalerter-win-x64.exe

**Your information**
Thomas Jenkins

**Comment by massimocandela** [comment]
From the error it looks like a config file is corrupted. Possibly an AS number in prefixes.yml.
I cannot reproduce the issue without more information: please, when opening an issue, don't wipe the bug report template.

**Comment by CyberBitz** [comment]
Thanks, I will run a few tests and post the configs

**Comment by CyberBitz** [comment]
This is with the 10421 AS. I changed the extension from yml to log for uploading
[config.log](https://github.com/nttgin/BGPalerter/files/6704680/config.log)


[prefixes.log](https://github.com/nttgin/BGPalerter/files/6704676/prefixes.log)

**Comment by massimocandela** [comment]
Thanks! I was able to reproduce it with your prefixes.yml. I made a patch that improves the validation of the prefixes.yml file, in particular the new downstreams/upstreams part.

Please, replace your executable with the one of [v1.28.1](https://github.com/nttgin/BGPalerter/releases/tag/v1.28.1). Let me know if you have any other problem.

Thanks for reporting.

**Comment by CyberBitz** [comment]
Awesome, thanks.

**Comment by massimocandela** [comment]
For whoever else has this issue with v1.28.0: open prefixes.yml and remove the "[]" in the downtreams/upstreams section
