### ISSUE TITLE
DockerHub: Latest stable image not tagged with "Latest"

### ISSUE THREAD

**Issue by chriselsen** [nttgin/BGPalerter#614]
In [Dockerhub](https://hub.docker.com/r/nttgin/bgpalerter/tags), the latest stable image (v1.28.1 from Jun 29, 2021) is not tagged with "latest". 
Instead image v1.27.1 from Jan 11, 2021 is tagged with "latest". 

Operators running BGPalerter via Docker therefore receive frequent update notifications.

**Comment by massimocandela** [comment]
Hi @chriselsen,

Thanks for reporting this! I just fixed the build trigger and now it's working again.
Please, let me know if you find any other problem.
