### ISSUE TITLE
display some progress indicator on 'generate'

### ISSUE THREAD

**Issue by nusenu** [nttgin/BGPalerter#63]
I'm running `generate` with a big input list (~3k prefixes) 
```
./bgpalerter-linux-x64 generate --pf prefixes.txt -o prefixes.yml
```
and it apparently takes a very long time (>1h) it would be nice to have some indicator that it does something and did not simply die or get stuck.

**Comment by massimocandela** [comment]
I think it is a good idea. 

Anyway, the time needed in your case is odd. I generate configurations for 10k+ prefixes in a few minutes. I would be curious to know where it hangs, maybe you can send me the list of prefixes?

**Comment by massimocandela** [comment]
Released in https://github.com/nttgin/BGPalerter/releases/tag/v1.22.0
