### ISSUE TITLE
Running with -t generate alerts but not when running normally

### ISSUE THREAD

**Issue by chuckbales** [nttgin/BGPalerter#648]
**Describe the bug**
I am trying to deploy BGPalerter for the first time and either I'm misunderstanding what the application does or I must be missing something obvious in my configuration. I provided our ASN when first launching the problem and it discovered prefixes automatically, I enabled the Slack webhook integration, but when I start advertising a new more specific prefix, I never receive an alert. I can see the update go out if I watch the RIS Live website directly, and if I run BGPalerter with `-t` I get all the test alerts in Slack correctly.

**Provide an example**
We have 170.163.0.0/16, with several smaller prefixes carved out currently. As a test I started advertising 170.163.232.0/24 explicitly to one of our peers. I was expecting to be alerted but nothing came into Slack or the reports file, though I saw the update on the RIS Live site.

[config.yml.txt](https://github.com/nttgin/BGPalerter/files/7164710/config.yml.txt)
[prefixes.yml.txt](https://github.com/nttgin/BGPalerter/files/7164711/prefixes.yml.txt)

**Are you using the binary or the source code?**
Binary 1.28.3

**Your information**
Charlie Bailey, AS10583

**Comment by massimocandela** [comment]
Hi @chuckbales,

Thanks for reporting this. I checked your specific case and tried to generate the monitoring rules multiple times. I found a bug where monitoring rules were overwriting each other. In particular, if you check the rule for `170.163.0.0/17` and set `ignoreMorespecifics: false` and `ignore: false`, you get correctly notified.
I fixed the issue and it will go out with the next release. If you want to give it a try, use the `release` branch (run the code or compile it yourself). 

Thanks a lot for reporting this!

**Comment by massimocandela** [comment]
Actually, since just the monitoring rule generator script was affected, if you use the attached file I generated for your AS with the new version of the code, you would be good to go with the current v1.28.3 release.

[prefixes.yml.txt](https://github.com/nttgin/BGPalerter/files/7169073/prefixes.yml.txt)
