### ISSUE TITLE
macOS binary, error if run without arguments

### ISSUE THREAD

**Issue by Antonio-Prado** [nttgin/BGPalerter#66]
Hi,

on macOS Darwin Kernel Version 17.7.0:
```
./bgpalerter-macos-x64.dms 
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: No prefixes to monitor in prefixes.yml
    at _loop (/snapshot/build/inputs/inputYml.js:167:19)
    at new InputYml (/snapshot/build/inputs/inputYml.js:198:9)
    at Object.<anonymous> (/snapshot/build/env.js:209:13)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:635:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
```
A help output is expected instead:

```
./bgpalerter-macos-x64.dms --help
Usage: bgpalerter-macos-x64.dms <command> [options]

Commands:
  bgpalerter-macos-x64.dms           Run BGPalerter (default)          [default]
  bgpalerter-macos-x64.dms generate  Generate prefixes to monitor

Options:
  --version   Show version number                                      [boolean]
  -h, --help  Show help                                                [boolean]

Examples:
  bgpalerter-macos-x64.dms run -c           Run BGPalerter
  config.yml
  bgpalerter-macos-x64.dms generate -a      Generate prefixes for AS2914
  2914 -o prefixes.yml

Copyright (c) 2019, NTT Ltd
```

thank you
--
antonio

**Comment by massimocandela** [comment]
Ciao Antonio,

Without parameters you run the default action, which is to monitor (as described in the --help).
The error is telling you that you didn't configure the prefix list to monitor in prefixes.yml.

Please, see here how to edit prefixes.yml or how to automatically generate the content: https://github.com/nttgin/BGPalerter/blob/master/README.md

**Comment by Antonio-Prado** [comment]
Massimo,

thank you for your quick reply.

It is just a request that may be useful to the lazy guy.
I mean: if I don't configure anything, I'd expect a friendly help, not an error without hints.

ciao
--
antonio

**Comment by massimocandela** [comment]
When you run it without configuring it, the binary realises you skipped some steps and it generates a default configuration and a default prefixes.yml. The prefix list is personal and so it is an empty file. Which is the result of the integration of https://github.com/nttgin/BGPalerter/issues/8

The error you get there says exactly **No prefixes to monitor in prefixes.yml** so it gives more than a hint.


```
./bgpalerter-macos-x64.dms 
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

--> Error: No prefixes to monitor in prefixes.yml <--
    at _loop (/snapshot/build/inputs/inputYml.js:167:19)
    at new InputYml (/snapshot/build/inputs/inputYml.js:198:9)
    at Object.<anonymous> (/snapshot/build/env.js:209:13)

```

For back compatibility I will keep supporting the default action and provide information in case something is wrong. 
In particular, since this is the only "error" that can happen in the default action, _I can add information on how to generate the prefix list directly in the error_. Does this address the issue?

**Comment by Antonio-Prado** [comment]
It does, well done.
Thank you
--
antonio

**Comment by massimocandela** [comment]
Released in https://github.com/nttgin/BGPalerter/releases/tag/v1.22.0

**Comment by massimocandela** [comment]
Even better addressed in https://github.com/nttgin/BGPalerter/releases/tag/v1.24.0
If config or prefixes are missing, a wizard will start.
