### ISSUE TITLE
New Prefix Alert by ASN

### ISSUE THREAD

**Issue by abrown-bw** [nttgin/BGPalerter#68]
It would be nice to have an alert for new prefixes advertised by ASNs configured in prefixes.yml which are not part of more specifics. BGPmon has this functionality and I find it useful. There are use cases where an aggregate can not be announced and any new announced prefixes within that aggregate are not picked up by BGPalerter even though the origin ASN is announcing prefixes listed in prefixes.yml.

**Comment by massimocandela** [comment]
Hi, I think I understand what you are asking. But please, could you provide me an example in terms of prefixes?

**Comment by abrown-bw** [comment]
Absolutely. Let's say I advertise 50.82.0.0/20 from ASN 58302 and have that prefix and origin ASN configured for BGPalerter along with alerting for new prefixes enabled. If I advertise 50.82.4.0/24 from ASN 58302 BGPalerter will tell me it has noticed a new prefix, however, if I announce 45.230.23.0/24 from ASN 58302 I will not get an alert. I would like to see alerts for all new prefixes by ASNs which are listed as origins for already monitored prefixes. Details about the observed AS path would also be beneficial to confirm transit input policies.

**Comment by massimocandela** [comment]
Released in https://github.com/nttgin/BGPalerter/releases/tag/v1.22.0
