### ISSUE TITLE
invoke generate-prefixes with docker

### ISSUE THREAD

**Issue by BenCastricum** [nttgin/BGPalerter#692]
We are experimenting with the docker version, but are unable to re-create the prefixes.yml non-interactively. This may also be due to my lack of knowledge of javascript. If that's the case a small pointer in the documentation would be very helpfull.

This is my most promising attempt:

```
sudo docker exec -ti bgpalerter npm run generate-prefixes -- -o prefixes-test.yml -a 12345

> bgpalerter@1.28.4 generate-prefixes /opt/bgpalerter
> babel-node index.js generate "-o" "prefixes-test.yml" "-a" "12345"

(node:293) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/opt/bgpalerter/index.js:33
import yargs from 'yargs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._compile (/opt/bgpalerter/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/opt/bgpalerter/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at Object.<anonymous> (/opt/bgpalerter/node_modules/@babel/node/lib/_babel-node.js:176:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bgpalerter@1.28.4 generate-prefixes: `babel-node index.js generate "-o" "prefixes-test.yml" "-a" "12345"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bgpalerter@1.28.4 generate-prefixes script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-05T15_17_51_740Z-debug.log
```

So my feature request would be:
A way to create the prefixes.yml without user interaction, using docker.

We need to alter a few settings in the config generated by default, so the idea is to have the standard generated prefixes.yml, alter it with a script and put the resulting yml file in the right place and restart the container to make the new config active. We want this to be a fully automatic process.

Thanks!

**Comment by massimocandela** [comment]
Hi @BenCastricum,

In Docker you are running the source code, so you must use `--` instead of `-` as specified [here](https://github.com/nttgin/BGPalerter/blob/23e3b33a60c00b51cc6310b3869b52e224984d00/docs/prefixes.md?plain=1#L7) and [here](https://github.com/nttgin/BGPalerter/blob/23e3b33a60c00b51cc6310b3869b52e224984d00/docs/prefixes.md?plain=1#L13). Otherwise you are passing parameters to the compiler and not to the application.

Also, once you edit prefixes.yml, you don't need to restart BGPalerter; the file is watched.

**Comment by BenCastricum** [comment]
Thanks, and I am sorry for wasting your time. I am off to buy some glasses :)
