### ISSUE TITLE
BGP alerter and ROA monitoring

### ISSUE THREAD

**Issue by skanda2000** [nttgin/BGPalerter#708]
I am interested to know, how BGP alerter add value if the upstream neighbors are dropping invalids ROAs (in the context of ROA monitoring)?

**Comment by massimocandela** [comment]
Hi @skanda2000,

ROAs are not "dropped". [ROAs are created and stored in public repos](https://www.ripe.net/manage-ips-and-asns/resource-management/rpki/resource-certification-roa-management).

ROA monitoring is performed based on the content of your VRP file or on a VRP file downloaded from a public repository (default). Diffing and filtering of this file is performed to check the resources of interest. [Read the documentation about monitorROA](https://github.com/nttgin/BGPalerter/blob/main/docs/configuration.md#monitorroas).

[RPKI monitoring](https://github.com/nttgin/BGPalerter/blob/main/docs/configuration.md#monitorrpki) is instead performed by comparing BGP data with the VRP file. The BGP data used by BGPalerter (default, [RIPE RIS](https://www.ripe.net/analyse/internet-measurements/routing-information-service-ris)) essentially shows how routers around the world are seeing/not seeing your resources. If all your neighbors do constant ROV (no periodic filters), you are not peering with RIPE RIS, and you are not feeding your own data into BGPalerter, then nobody except your neighbors will be able to see your invalids (and BGPalerter will not inform you).
