### ISSUE TITLE
Feature Request: Add an nickname string that identifies the BGPalerter instance to notifications

### ISSUE THREAD

**Issue by mfld-pub** [nttgin/BGPalerter#734]
**Describe what you would like to achieve**
I would like a configurable string that is sent along with notifications to identify which instance made the report.

**Describe why the current solution (if any) is not satisfactory**
Since #535 I ended up keeping two instances up in different vantage points to keep an eye on instances where events are missed. 
They report to the same slack channel / Telegram Group. It is impossible to distinguish which instance made a report. 

My workaround is to put them in different channels, give them different e-mail accounts, etc. But it would be a nice to have bonus feature if an instance could be nicknamed and this be part of reports.

**Comment by massimocandela** [comment]
Hi @mfld-pub,

This can be already achieved with [templates](https://github.com/nttgin/BGPalerter/blob/main/docs/context.md), in your case (e.g., in combination with reportHTTP or reportEmail). You can simply add a string in front of `${summary}`.

However, related to https://github.com/nttgin/BGPalerter/issues/535. Now BGPalerter subscribes to some prefixes called [RIS beacons](https://www.ripe.net/analyse/internet-measurements/routing-information-service-ris/current-ris-routing-beacons). RIS beacons are prefixes periodically announced and  withdrawn. BGPalerter knows when those prefixes should be announced/withdrawn, and if no BGP message is collected for a certain period of time, an error is triggered and a new connection is attempted. This is to cover also the case in which the connection is "up" but no data is received. In particular, if you use any of the process monitors (e.g., healthcheck, uptimeApi), these would report the monitoring as down before a new working connection is established.
