### ISSUE TITLE
Auto generate prefixes using the binary

### ISSUE THREAD

**Issue by Epaphus** [nttgin/BGPalerter#8]
Is is possible to generate the prefix file with the binary version without needing to install NodeJS just to run the generate-prefixes npm command?

**Comment by wk** [comment]
Second this; not having the 'generate-prefixes' functionality within the main executable resulting from 'npm build' makes packaging and distribution more challenging; having the generate-prefixes functionality as a run-time argument of the primary script would greatly simplify this. 

Additionally, it'd be convenient if the included `prefixes.yml` and `config.yml` files were embedded in the binary resulting from 'npm build' and written out to disk (either in the current path, or in a predetermined configuration directory for each platform) upon initial invocation of the binary if they are not present.

Together these changes will enable distributing BGPalerter as a single binary with ease.

**Comment by massimocandela** [comment]
The latest release contains these features
