### ISSUE TITLE
Feature request: Mattermost reporter

### ISSUE THREAD

**Issue by fstolba** [nttgin/BGPalerter#81]
Mattermost is a popular open-source, self-hosting capable alternative to Slack. It would be highly appreciated if you could look into creating a reporter for that platform. 

If you decide to implement it I would definitely be willing to test and provide feedback.

**Comment by massimocandela** [comment]
Hello,

The Mattermost integration is now available with the [reportHTTP](https://github.com/nttgin/BGPalerter/blob/dev/docs/configuration.md#reporthttp) module. This is currently deployed in dev. Please, provide me with feedback. In particular we could describe a specific set of templates for mattermost.

**Comment by fstolba** [comment]
Hi Massimo,
great, having a general webhook mechanism is certainly the most flexible approach. I will give it a try and report back.

**Comment by fstolba** [comment]
So I finally came around to testing the reporter module and as far as I tested it works flawlessly. 

The config we're using it with:

```
# Report to Mattermost channel
reports:
  - file: reportHTTP
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
    params:
      templates:
        default: '
  {"attachments": [
  {"fields": [ {"title": "Prefix:", "value": "${prefix}", "short": "false"},
  {"title": "Expected from:", "value": "AS ${asn}", "short": "true"},
  {"title": "Seen from:", "value": "AS ${neworigin}", "short": "true"},
  {"title": "Since:", "value": "${earliest}", "short": "true"},
  {"title": "Details:", "value": "[BGPlay](${bgplay})", "short": "true"},
  {"title": "Event description":, "value": "${summary}"} ], 
  "text": "#bgpalerter #${type}", "color": "#ffffff"}]}'
        visibility: '
  {"attachments": [
  {"fields": [ {"title": "Prefix:", "value": "${prefix}", "short": "false"},
  {"title": "Originating from:", "value": "AS ${asn}", "short": "true"},
  {"title": "Since:", "value": "${earliest}", "short": "true"},
  {"title": "Details:", "value": "[BGPlay](${bgplay})", "short": "true"},
  {"title": "Event description", "value": "${summary}"} ], 
  "text": "#bgpalerter #${type}", "color": "#ffffff"}]}'
      isTemplateJSON: true
      headers:
      showPaths: 0 # Amount of AS_PATHs to report in the alert
      hooks:
        default: WEBHOOK_URL
``` 

which results in messages like these

![grafik](https://user-images.githubusercontent.com/2249547/81048395-8d123d00-8ebc-11ea-9977-d0bdb7662fba.png)


Adding additional properties or modifying field descriptions can be easily done by adapting the `fields` array.

**Comment by massimocandela** [comment]
Hi @fstolba,

This is great! 
I'm going to create a documentation page dedicated to mattermost and provide the template you wrote. 

Ciao,
Massimo

**Comment by fstolba** [comment]
Glad I could be of help. Thanks again @massimocandela for implementing this feature, it helps integrate BGPalerter much more seamlessly with our other tools.

**Comment by massimocandela** [comment]
Hi @fstolba, I added this here: https://github.com/nttgin/BGPalerter/blob/dev/docs/report-http.md#mattermost Thanks
