### ISSUE TITLE
A status page of currently monitored prefixes and ASNs

### ISSUE THREAD

**Issue by kaon1** [nttgin/BGPalerter#875]
**Describe what you would like to achieve**
Provide a REST API page of currently monitored prefixes and ASNs. 

**Describe why the current solution (if any) is not satisfactory**
I would like to regularly poll the status and make sure we are monitoring what is expected without having to login to the server and check the prefix.yml config file.

**Comment by massimocandela** [comment]
Hi @kaon1,

Sorry for the delay. I was thinking about this, but I'm not 100% sold on this feature. It sounds trivial, but each api endpoint is more code to maintain. (For now you could serve the file with nginx, even converted on-fly to json).
