### ISSUE TITLE
Tighten up descriptions in some alerts

### ISSUE THREAD

**Issue by falz** [nttgin/BGPalerter#940]
Cosmetic suggestion. TLDR: tweak alert texts to be 'just the facts'.

Some alerts have some extra text in them that seems unneccessary. When a new prefix is found, `monitorNewPrefix.js` has this text:

```
Possible change of configuration. A new prefix ${message.prefix} is announced by ${message.originAS}. It is a more specific of ${matchedRule.prefix} (${matchedRule.description})
```

Suggestion to eliminate the `Possible change of configuration.` to keep it concise and remove speculation which could be a red herring to a network operator that sees the alert. Ie cause could be anything - config change, circuit down, device down, etc.

This was the only alert message that seemed to have this "issue". Cheers

**Comment by massimocandela** [comment]
Hi @falz,

The `Possible change of configuration` refers to the BGPalerter configuration (and not routing). The original idea was to prompt the user to update the list of prefixes with the new prefix (if legit). Some users don't update the prefix list and the BGPalerter installation becomes noisy over time.

However, I do see your point. The current phrasing may complicate things without really convey what I meant. Let's see if I can find a better wording that would allow me to keep the suggestion of updating prefixes.yml.

**Comment by falz** [comment]
That description of Configuration makes sense, thanks. I guess it was enough of a red herring to confuse myself!

**Comment by massimocandela** [comment]
Hi @falz,

I changed the summary (self explanatory [here](https://github.com/nttgin/BGPalerter/blob/22a7332c5359203a6123ce2be70192e0fa42b306/src/monitors/monitorNewPrefix.js#L59)). This will go out with the next release.
