### ISSUE TITLE
support for the matrix open standard protocol. https://matrix.org/

### ISSUE THREAD

**Issue by ronnyaa** [nttgin/BGPalerter#977]
It would be great if BGPalerter could support the matrix open chat protocol, for alerting. 
any company can via their own matrix homeserver bridge that into even more unsupported tools. 

A example for how to send a message via curl can be found here
https://gist.github.com/travnewmatic/769cd9532504e0f85983d69acd4a7d29

best regards
Ronny Aasen

**Comment by massimocandela** [comment]
Hi @ronnyaa,

I'm ok with that. But please, provide a pull request. The pull request can include code, or a snippet of configuration to use with reportHTTP (e.g., https://github.com/nttgin/BGPalerter/blob/main/docs/report-http.md).

**Comment by massimocandela** [comment]
Done in https://github.com/nttgin/BGPalerter/pull/1043
